### ISSUE TITLE
在已有项目中添加自定义子模块

### ISSUE THREAD

**Issue by 9Cirno9** [SYaoJun/CMakeTutorial#2]
大佬好，我现在有一个cmake+vs2022构建的项目
![image](https://github.com/user-attachments/assets/d8c7d6dd-dd02-44ef-9849-5930b915c33a)
然后我想在module文件夹里添加自己定义的功能模块
![image](https://github.com/user-attachments/assets/fb74dbe9-d247-4291-aa5f-4fbae359ce86)
然后对应的qt界面放到UI文件夹中
请问如何操作呢

**Comment by SYaoJun** [comment]
可以新建一个文件夹，在新文件夹里面添加cmakelist.txt

**Comment by SYaoJun** [comment]
Do you have any problems? I will consider closing this issue

**Comment by 9Cirno9** [comment]
> Do you have any problems? I will consider closing this issue

没有问题了，非常感谢！
